import "./globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import {Providers} from "./providers"
import {Roboto} from "next/font/google"
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400' ,'700'],
  display: 'swap'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <Providers>
        <Navigation/> 
        {children}
          <Footer/>
        </Providers>
        </body>
    </html>
  );
}
